version: '3'

services:
    caddy:
        image: caddy:latest
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./proxy/Caddyfile:/etc/caddy/Caddyfile
        networks:
            - proxyNetwork
    backend:
        image: crypto-tracker-backend:latest
        build:
            context: ./backend
            dockerfile: Dockerfile
        networks:
            - proxyNetwork
    frontend:
        image: crypto-tracker-frontend:latest
        build:
            context: ./frontend
            dockerfile: Dockerfile
        ports:
            - 3000:3000
        depends_on:
            - backend
        networks:
            - proxyNetwork

networks:
    proxyNetwork:
