version: '3'

services:
    caddy:
        image: caddy:latest
        networks:
            - proxyNetwork
    backend:
        image: crypto-tracker-backend:latest
        build:
            context: ./backend
            dockerfile: Dockerfile
        env_file:
            - ./backend/.env
        ports:
            - 8080:8080
        networks:
            - proxyNetwork
    frontend:
        image: crypto-tracker-frontend:latest
        build:
            context: ./frontend
            dockerfile: Dockerfile
        ports:
            - 3000:3000
        depends_on:
            - backend
        networks:
            - proxyNetwork

networks:
    proxyNetwork:
